---
- name: HOST SETUP
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    url: flasharray1.testdrive.local
    api: e448c603-ecfd-8b4e-fc02-0d742e81a779
    ansible_hostname: ansiblehost
    ansible_iscsi_iqn: iqn.1994-05.com.redhat:ansible_hostname
  tasks:
    - name: CREATE HOST
      purestorage.flasharray.purefa_host:
        name: "{{ ansible_hostname }}"
        iqn: "{{ ansible_iscsi_iqn }}"
        fa_url: "{{ url }}"
        api_token: "{{ api }}"
