---
- name: ASYNC SETUP
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    url: flasharray1.testdrive.local
    api: e448c603-ecfd-8b4e-fc02-0d742e81a779
    target_url: flasharray2.testdrive.local
    target_api: ace81cf0-7c6d-98a4-ff12-13c4c1cc14b3
  tasks:
    - name: TARGET INFO
      purestorage.flasharray.purefa_info:
        fa_url: "{{ target_url }}"
        api_token: "{{ target_api }}"
      register: target_array

    - name: UPDATE PG
      purestorage.flasharray.purefa_pg:
        name: workshop-pg
        target: "{{ target_array['purefa_info']['default']['array_name'] }}"
        fa_url: "{{ url }}"
        api_token: "{{ api }}"
